#!/bin/bash


if [ ${#KAFKA_REST_CONSUMER_INSTANCE_TIMEOUT_MS} != 0 ]; then
  echo "Hello Alan.1:${KAFKA_REST_CONSUMER_INSTANCE_TIMEOUT_MS}."
  echo "consumer.instance.timeout.ms=${KAFKA_REST_CONSUMER_INSTANCE_TIMEOUT_MS}" >> /etc/kafka-rest/kafka-rest.properties
fi

if [ ${#KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS} != 0 ]; then
  echo "Hello Alan.2"
  echo "consumer.request.timeout.ms=${KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS}" >> /etc/kafka-rest/kafka-rest.properties
fi

if [ ${#KAFKA_REST_CONSUMER_REQUEST_MAX_BYTES} != 0  ]; then
  echo "consumer.request.max.bytes=${KAFKA_REST_CONSUMER_REQUEST_MAX_BYTES}" >> /etc/kafka-rest/kafka-rest.properties
  echo "Hello Alan.3"
fi

echo "#generated by start-kafka-rest.sh at $(date)" >> /etc/kafka-rest/kafka-rest.properties

exec ./opt/confluent/bin/kafka-rest-start /etc/kafka-rest/kafka-rest.properties
